/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery.system;

import SQL_Connector.Connector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class BILLING_SPECIAL extends javax.swing.JFrame {

    /**
     * Creates new form BILLING_SPECIAL
     */
    public BILLING_SPECIAL() {
        initComponents();
        displayTime();

    }
    
    public void displayTime(){
        
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                java.text.SimpleDateFormat simpleDateFormat = new java.text.SimpleDateFormat("HH:mm:ss");
                
                String text_displayTime = simpleDateFormat.format(new Date());
                
                String text_displayDate = new SimpleDateFormat("dd/MM/yyyy",Locale.ENGLISH).format(new Date());
                
                date_time.setText(text_displayDate + " " + text_displayTime);
            }
            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        date_time = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        itemId = new javax.swing.JTextField();
        itemName = new javax.swing.JTextField();
        itemPrice = new javax.swing.JTextField();
        itemQuantity = new javax.swing.JSpinner();
        add = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        specialPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        netAmount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtcash = new javax.swing.JTextField();
        bill = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        IDBILL = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        netTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        custom = new javax.swing.JTextField();
        hello = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("SURAMYAS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        date_time.setEditable(false);
        date_time.setBackground(new java.awt.Color(102, 0, 102));
        date_time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date_time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 50));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Net Amount");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, 24));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Item Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("Quantity");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("Price");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("Amount");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        amount.setEditable(false);
        jPanel2.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 100, 40));

        itemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdActionPerformed(evt);
            }
        });
        itemId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemIdKeyReleased(evt);
            }
        });
        jPanel2.add(itemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 40));

        itemName.setEditable(false);
        jPanel2.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 40));

        itemPrice.setEditable(false);
        jPanel2.add(itemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 100, 40));

        itemQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                itemQuantityStateChanged(evt);
            }
        });
        jPanel2.add(itemQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 90, 40));

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("Item ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 24));

        specialPrice.setEditable(false);
        jPanel2.add(specialPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 100, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("SPECIAL PRICE");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 130, 24));

        netAmount.setEditable(false);
        jPanel2.add(netAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 737, 300));

        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item_ID", "Item_Name", "Quantity", "Price", "Special Price", "Amount", "Net Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 730, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Balance");

        txtbalance.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cash");

        txttotal.setEditable(false);

        bill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bill.setText("BILL");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Bill ID");

        IDBILL.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Discounts");

        txtdiscount.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Net Total");

        netTotal.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txttotal, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(IDBILL)
                            .addComponent(netTotal))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDBILL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(netTotal)
                        .addGap(8, 8, 8)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcash, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 9, 400, 390));

        txtbill.setEditable(false);
        txtbill.setColumns(20);
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 399, 240));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, 139, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer ID");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 40));

        custom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        custom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customKeyReleased(evt);
            }
        });
        jPanel1.add(custom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 370, 30));

        hello.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hello.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 530, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdKeyPressed

    private void itemIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemIdKeyReleased
        get_data(itemId.getText());
    }//GEN-LAST:event_itemIdKeyReleased

    private void itemQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_itemQuantityStateChanged
        int qty = Integer.parseInt(itemQuantity.getValue().toString());
        int price = Integer.parseInt(itemPrice.getText());
        
        int sp_price = Integer.parseInt(specialPrice.getText());

        int tot = qty * price;
        
        int net_tot = qty * sp_price;

        amount.setText(String.valueOf(tot));
        
        netAmount.setText(String.valueOf(net_tot));
    }//GEN-LAST:event_itemQuantityStateChanged

    
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        DefaultTableModel model = new DefaultTableModel();

        model = (DefaultTableModel)itemTable.getModel();

        model.addRow(new Object[]

            {
                itemId.getText(),
                itemName.getText(),
                itemQuantity.getValue().toString(),
                itemPrice.getText(),
                specialPrice.getText(),
                amount.getText(),
                netAmount.getText()
            } );

            int sum = 0;
            int net_sum = 0;
            for(int i = 0; i < itemTable.getRowCount(); i++)
            {
                sum = sum + Integer.parseInt(itemTable.getValueAt(i, 5).toString());
                net_sum = net_sum + Integer.parseInt(itemTable.getValueAt(i, 6).toString());
            }

            txttotal.setText(Integer.toString(sum));
            netTotal.setText(Integer.toString(net_sum));

            itemId.setText("");
            itemName.setText("");
            itemPrice.setText("");
            specialPrice.setText("");
            amount.setText("");
            netAmount.setText("");
            itemId.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        discount();
        balance();
        Bill_ID();
        bill();
        ADD_BILL();


    }//GEN-LAST:event_billActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
            txtbill.print();
        } catch (PrinterException ex) {
            Logger.getLogger(BILLING_NORMAL.class.getName()).log(Level.SEVERE, null, ex);
        }
        new HOME_PAGE().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdActionPerformed

    private void customKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customKeyReleased
        greetings(custom.getText());
    }//GEN-LAST:event_customKeyReleased

    public void Bill_ID(){
        Random rand = new Random();
        
        int maxNumber = 100000;
        
        int bill_identity = rand.nextInt(maxNumber) + 1;

        IDBILL.setText(String.valueOf(bill_identity));
    }
    
     public void ADD_BILL()
    {
        String bill_identity = IDBILL.getText();
         
        String date = date_time.getText();
               
        int net_total = Integer.parseInt(netTotal.getText());

        
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO bill_log VALUES ('"+bill_identity+"','"+date+"',"+net_total+")";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Data Insert Successfully !!");
           
           
           JOptionPane.showMessageDialog(null,"DONE!!!!");

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
           
    }
     
     public void get_data(String id)
    {
        Integer bid = Integer.valueOf(id);
        
        
        String SQL = "SELECT * FROM grocery_items WHERE ITEM_ID = "+id+"";
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
           
            
                while(rs.next())
                {
                    itemName.setText(rs.getString("ITEM_NAME"));
                    itemPrice.setText(rs.getString("PRICE"));
                    specialPrice.setText(rs.getString("CUSTOM_PRICE"));

                }
            
            
         }
                
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
     
     public void greetings(String id)
    {
        Integer bid = Integer.valueOf(id);
        
        
        String SQL = "SELECT * FROM customers WHERE CUSTOMER_ID = "+id+"";
        
         java.sql.Connection connection = Connector.connection();
         
         try
         {
            Statement stmt = connection.createStatement();
            
            ResultSet rs = stmt.executeQuery(SQL);
           
            
                while(rs.next())
                {
                    hello.setText(rs.getString("CUSTOMER_NAME"));
                    

                }
            
            
         }
                
         catch(Exception ERROR)
         {
             System.out.println(ERROR);
         }
    
    }
     
     public void balance (){
        
        int net_total = Integer.parseInt(netTotal.getText());
        int cash = Integer.parseInt(txtcash.getText());
        
        int bal = cash - net_total;
        
        txtbalance.setText(String.valueOf(bal));   
        
    }
     
    public void discount (){
        
        int total = Integer.parseInt(txttotal.getText());
        
        int net_total = Integer.parseInt(netTotal.getText());
        
        int disc = total - net_total;
        
        txtdiscount.setText(String.valueOf(disc));
    }
    
    public void bill(){
        
        String total = txttotal.getText();
        String net_total = netTotal.getText();
        String cash = txtcash.getText();
        String bal = txtbalance.getText();
        String timer = date_time.getText();
        String disc = txtdiscount.getText();
        String user = hello.getText();
        
        DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)itemTable.getModel();
        
        txtbill.setText(txtbill.getText() + "                       SURAMYAS                \n");
        txtbill.setText(txtbill.getText() + "------------------------------------------------\n");        
        txtbill.setText(txtbill.getText() + "   No 55, Perera Mawatha, Thalawathugoda         \n");
        txtbill.setText(txtbill.getText() + "   Contact us: 0771980543 0764354565              \n");
        txtbill.setText(txtbill.getText() + "   " + timer + "\n");

        txtbill.setText(txtbill.getText() + "------------------------------------------------\n");        
        


        //Heading
        txtbill.setText(txtbill.getText() + "Product" + "\t" + "Price" + "\t" + "Quantity"+ "\t" +"Amount" + "\t" +"Net Amount" + "\n");

        for(int i = 0; i < model.getRowCount(); i++){
            
            String iname = (String)model.getValueAt(i, 1);
            String price = (String)model.getValueAt(i, 3);
            String quantity = (String)model.getValueAt(i, 2);
            String amount = (String)model.getValueAt(i, 5);
            String net_amount = (String)model.getValueAt(i, 6);
            
            txtbill.setText(txtbill.getText() + iname + "\t" + price + "\t" + quantity + "\t" + amount + "\t" +  net_amount + "\n");


        }
        
        txtbill.setText(txtbill.getText() + "\n");

        txtbill.setText(txtbill.getText() + "Sub Total :" + "\t" + "\t" + "\t" + "\t" + total + "\n");
        txtbill.setText(txtbill.getText() + "Discount :" + "\t" + "\t" + "\t" + "\t" + disc+ "\n");
        txtbill.setText(txtbill.getText() + "Net Total :" + "\t" + "\t" + "\t" + "\t" + net_total+ "\n");
        txtbill.setText(txtbill.getText() + "Cash :" + "\t" + "\t" + "\t" + "\t" +cash+ "\n");
        txtbill.setText(txtbill.getText() + "____________________________________\n");
        txtbill.setText(txtbill.getText() + "Balance :" + "\t" + "\t" + "\t" + "\t" + bal+ "\n");

        txtbill.setText(txtbill.getText() + "\n");
        txtbill.setText(txtbill.getText() + "____________________________________\n");
        txtbill.setText(txtbill.getText() + "       Thank You" + " " + user + " " + " Come Again.       \n");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BILLING_SPECIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BILLING_SPECIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BILLING_SPECIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BILLING_SPECIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BILLING_SPECIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDBILL;
    private javax.swing.JButton add;
    private javax.swing.JTextField amount;
    private javax.swing.JButton bill;
    private javax.swing.JTextField custom;
    private javax.swing.JTextField date_time;
    private javax.swing.JTextField hello;
    private javax.swing.JTextField itemId;
    private javax.swing.JTextField itemName;
    private javax.swing.JTextField itemPrice;
    private javax.swing.JSpinner itemQuantity;
    private javax.swing.JTable itemTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField netAmount;
    private javax.swing.JTextField netTotal;
    private javax.swing.JTextField specialPrice;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JTextField txtcash;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
