/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery.system;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class HOME_PAGE extends javax.swing.JFrame {

    /**
     * Creates new form HOME_PAGE
     */
    public HOME_PAGE() {
        initComponents();
        displayTime();
    }
    
    public void displayTime(){
        
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                java.text.SimpleDateFormat simpleDateFormat = new java.text.SimpleDateFormat("HH:mm:ss");
                
                String text_displayTime = simpleDateFormat.format(new Date());
                
                String text_displayDate = new SimpleDateFormat("dd/MM/yyyy",Locale.ENGLISH).format(new Date());
                
                date_time.setText(text_displayDate + " " + text_displayTime);
            }
            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        viewCustomers = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        viewUpdateItems = new javax.swing.JButton();
        businessRecords = new javax.swing.JButton();
        customerRegistration = new javax.swing.JButton();
        addRemoveItems = new javax.swing.JButton();
        billing = new javax.swing.JButton();
        date_time = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setText("SURAMYAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 23, 298, 76));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewCustomers.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewCustomers.setForeground(new java.awt.Color(0, 153, 153));
        viewCustomers.setText("VIEW CUSTOMERS");
        viewCustomers.setPreferredSize(new java.awt.Dimension(111, 41));
        viewCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomersActionPerformed(evt);
            }
        });
        jPanel1.add(viewCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 296, 70));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 153, 153));
        exit.setText("EXIT");
        exit.setPreferredSize(new java.awt.Dimension(111, 41));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 270, 70));

        viewUpdateItems.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewUpdateItems.setForeground(new java.awt.Color(0, 153, 153));
        viewUpdateItems.setText("VIEW & UPDATE ITEMS");
        viewUpdateItems.setPreferredSize(new java.awt.Dimension(111, 41));
        viewUpdateItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUpdateItemsActionPerformed(evt);
            }
        });
        jPanel1.add(viewUpdateItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 270, 70));

        businessRecords.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        businessRecords.setForeground(new java.awt.Color(0, 153, 153));
        businessRecords.setText("BUSINESS RECORDS");
        businessRecords.setPreferredSize(new java.awt.Dimension(111, 41));
        businessRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRecordsActionPerformed(evt);
            }
        });
        jPanel1.add(businessRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 270, 70));

        customerRegistration.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        customerRegistration.setForeground(new java.awt.Color(0, 153, 153));
        customerRegistration.setText("CUSTOMER REGISTRATION");
        customerRegistration.setPreferredSize(new java.awt.Dimension(111, 41));
        customerRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRegistrationActionPerformed(evt);
            }
        });
        jPanel1.add(customerRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 296, 70));

        addRemoveItems.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addRemoveItems.setForeground(new java.awt.Color(0, 153, 153));
        addRemoveItems.setText("ADD & REMOVE ITEMS");
        addRemoveItems.setPreferredSize(new java.awt.Dimension(111, 41));
        addRemoveItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRemoveItemsActionPerformed(evt);
            }
        });
        jPanel1.add(addRemoveItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 270, 70));

        billing.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        billing.setForeground(new java.awt.Color(0, 153, 153));
        billing.setText("BILLING");
        billing.setPreferredSize(new java.awt.Dimension(111, 41));
        billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingActionPerformed(evt);
            }
        });
        jPanel1.add(billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 270, 70));

        date_time.setEditable(false);
        date_time.setBackground(new java.awt.Color(51, 0, 102));
        date_time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date_time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 740, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRegistrationActionPerformed

        new REGISTER_CUSTOMERS().setVisible(true);
    }//GEN-LAST:event_customerRegistrationActionPerformed

    private void viewCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomersActionPerformed
        new VIEW_CUSTOMERS().setVisible(true);

    }//GEN-LAST:event_viewCustomersActionPerformed

    private void addRemoveItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRemoveItemsActionPerformed
       new ADD_AND_REMOVE_GROCERY_ITEMS().setVisible(true);

    }//GEN-LAST:event_addRemoveItemsActionPerformed

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
        new BILLING().setVisible(true);

    }//GEN-LAST:event_billingActionPerformed

    private void viewUpdateItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUpdateItemsActionPerformed
        new VIEW_UPDATE_GROCERY_ITEMS().setVisible(true);

    }//GEN-LAST:event_viewUpdateItemsActionPerformed

    private void businessRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRecordsActionPerformed
        new BUSINESS_RECORDS().setVisible(true);

    }//GEN-LAST:event_businessRecordsActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        close_window();
    }//GEN-LAST:event_exitActionPerformed

    public void close_window()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME_PAGE().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRemoveItems;
    private javax.swing.JButton billing;
    private javax.swing.JButton businessRecords;
    private javax.swing.JButton customerRegistration;
    private javax.swing.JTextField date_time;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton viewCustomers;
    private javax.swing.JButton viewUpdateItems;
    // End of variables declaration//GEN-END:variables
}
