/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grocery.system;

import SQL_Connector.Connector;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author HP
 */
public class REGISTER_CUSTOMERS extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER_CUSTOMERS
     */
    public REGISTER_CUSTOMERS() {
        initComponents();
        displayTime();
    }
    
    public void displayTime(){
        
        new Timer(0, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                
                java.text.SimpleDateFormat simpleDateFormat = new java.text.SimpleDateFormat("HH:mm:ss");
                
                String text_displayTime = simpleDateFormat.format(new Date());
                
                String text_displayDate = new SimpleDateFormat("dd/MM/yyyy",Locale.ENGLISH).format(new Date());
                
                date_time.setText(text_displayDate + " " + text_displayTime);
            }
            
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        date_time = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        member_ID = new javax.swing.JLabel();
        customerId = new javax.swing.JTextField();
        SLTC = new javax.swing.JLabel();
        customerName = new javax.swing.JTextField();
        pnumber = new javax.swing.JLabel();
        customerAddress = new javax.swing.JTextField();
        nnumber = new javax.swing.JLabel();
        customerContactNumber = new javax.swing.JTextField();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("SURAMYAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fbab574b1f60680c17ae6e9cce995bee.gif"))); // NOI18N
        jLabel4.setText("LIBRARY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, 510, 210));

        date_time.setEditable(false);
        date_time.setBackground(new java.awt.Color(51, 0, 153));
        date_time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date_time.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(date_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 520, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 580));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("REGISTER CUSTOMERS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 290, 130));

        member_ID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        member_ID.setText("CUSTOMER ID");
        getContentPane().add(member_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, 50));

        customerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdActionPerformed(evt);
            }
        });
        getContentPane().add(customerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 320, 40));

        SLTC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SLTC.setText("CUSTOMER NAME");
        getContentPane().add(SLTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 150, 80));
        getContentPane().add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 320, 40));

        pnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pnumber.setText("EMAIL ADDRESS");
        getContentPane().add(pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 150, 80));
        getContentPane().add(customerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 320, 40));

        nnumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nnumber.setText("CONTACT NUMBER");
        getContentPane().add(nnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 170, 80));
        getContentPane().add(customerContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 320, 40));

        register.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 0, 102));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        Add_data();
    }//GEN-LAST:event_registerActionPerformed

     public void close_window()
    {
        WindowEvent new_event;
        
        new_event = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(new_event);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER_CUSTOMERS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER_CUSTOMERS().setVisible(true);
            }
        });
    }
    
     public void Add_data()
    {
        
        String customer_ID = customerId.getText();
        
        String customer_name = customerName.getText();
        
        String customer_address = customerAddress.getText();
        
        String contact_number = customerContactNumber.getText();
        
        
        java.sql.Connection connection = Connector.connection();
        
        String SQL = "INSERT INTO customers VALUES ('"+customer_ID+"','"+customer_name+"','"+customer_address+"','"+contact_number+"')";
        
        
        try
        {
           PreparedStatement preparedStatement = connection.prepareStatement(SQL);

           preparedStatement.executeUpdate();
           
           System.out.println("Data Insert Successfully !!");
           
           JOptionPane.showMessageDialog(null,"Customer Added to the System Successfully !!");
           new HOME_PAGE().setVisible(true);

        }
        catch(Exception error)
        {
            System.out.println("ERROR CODE : "+error);
            
            JOptionPane.showMessageDialog(null,"Attempt Unsuccessful");
        }
        
        
       
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SLTC;
    private javax.swing.JTextField customerAddress;
    private javax.swing.JTextField customerContactNumber;
    private javax.swing.JTextField customerId;
    private javax.swing.JTextField customerName;
    private javax.swing.JTextField date_time;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel member_ID;
    private javax.swing.JLabel nnumber;
    private javax.swing.JLabel pnumber;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
